### ISSUE TITLE
what does it do?

### ISSUE THREAD

**Issue by cornernote** [paramat/meru#1]
Looks interesting, but I'm not sure what it's supposed to do.

Could you add some more to the readme about this?

**Comment by paramat** [comment]
https://forum.minetest.net/viewtopic.php?f=11&t=5159&hilit=meru

**Comment by cornernote** [comment]
Would you mind if I add some more info to the readme and format it as markdown?

**Comment by paramat** [comment]
Sorry i don't like markdown format and would want to write my own readme, thanks anyway.
